#!/bin/bash
set -euo pipefail

# DeploySentry Development Setup Script
# Automatically sets up a complete local development environment

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ ${1}${NC}"
}

log_success() {
    echo -e "${GREEN}✅ ${1}${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️ ${1}${NC}"
}

log_error() {
    echo -e "${RED}❌ ${1}${NC}"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."

    local missing=()

    if ! command_exists docker; then
        missing+=("Docker")
    fi

    if ! command_exists go; then
        missing+=("Go 1.22+")
    fi

    if ! command_exists node; then
        missing+=("Node.js 18+")
    fi

    if ! command_exists migrate; then
        log_warning "migrate CLI not found, will install..."
    fi

    if [ ${#missing[@]} -ne 0 ]; then
        log_error "Missing prerequisites: ${missing[*]}"
        log_info "Please install the missing tools and re-run this script"
        exit 1
    fi

    log_success "All prerequisites satisfied"
}

# Install migrate CLI if missing
install_migrate() {
    if ! command_exists migrate; then
        log_info "Installing golang-migrate CLI..."
        go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
        log_success "migrate CLI installed"
    fi
}

# Generate development environment file
generate_env_file() {
    log_info "Generating development .env file..."

    local env_file="$PROJECT_ROOT/.env"

    if [ -f "$env_file" ]; then
        log_warning ".env file already exists, backing up to .env.backup"
        cp "$env_file" "$env_file.backup"
    fi

    # Generate a secure JWT secret for development
    local jwt_secret
    jwt_secret=$(openssl rand -base64 64 | tr -d '\n')

    cat > "$env_file" << EOF
# =============================================================================
# DeploySentry Development Environment
# Auto-generated by dev-setup.sh on $(date)
# =============================================================================

# Environment
DS_ENVIRONMENT=development

# Server Configuration
DS_SERVER_HOST=0.0.0.0
DS_SERVER_PORT=8080
DS_SERVER_READ_TIMEOUT=15s
DS_SERVER_WRITE_TIMEOUT=15s
DS_SERVER_SHUTDOWN_TIMEOUT=10s

# Database (PostgreSQL) Configuration
DS_DATABASE_HOST=localhost
DS_DATABASE_PORT=5432
DS_DATABASE_USER=deploysentry
DS_DATABASE_PASSWORD=deploysentry
DS_DATABASE_NAME=deploysentry
DS_DATABASE_SCHEMA=deploy
DS_DATABASE_SSL_MODE=disable
DS_DATABASE_MAX_OPEN_CONNS=25
DS_DATABASE_MAX_IDLE_CONNS=10
DS_DATABASE_CONN_MAX_LIFETIME=5m

# Redis Configuration
DS_REDIS_HOST=localhost
DS_REDIS_PORT=6379
DS_REDIS_PASSWORD=
DS_REDIS_DB=0

# NATS Configuration
DS_NATS_URL=nats://localhost:4222
DS_NATS_MAX_RECONNECTS=10
DS_NATS_RECONNECT_WAIT=2s
DS_NATS_CONNECT_TIMEOUT=5s

# Authentication (Development - Generated)
DS_AUTH_JWT_SECRET=${jwt_secret}
DS_AUTH_JWT_EXPIRATION=24h
DS_AUTH_OAUTH2_CLIENT_ID=
DS_AUTH_OAUTH2_CLIENT_SECRET=
DS_AUTH_OAUTH2_REDIRECT_URL=http://localhost:8080/auth/callback

# Logging
DS_LOG_LEVEL=debug
DS_LOG_FORMAT=text

# Application Version
DS_VERSION=dev
EOF

    log_success "Development .env file created with secure JWT secret"
}

# Start development services
start_services() {
    log_info "Starting development services (PostgreSQL, Redis, NATS)..."

    cd "$PROJECT_ROOT"

    # Stop any existing containers to ensure clean state
    docker-compose -f deploy/docker-compose.yml down >/dev/null 2>&1 || true

    # Start services
    docker-compose -f deploy/docker-compose.yml up -d

    # Wait for services to be ready
    log_info "Waiting for services to be ready..."
    sleep 10

    # Test PostgreSQL connection
    local max_attempts=30
    local attempt=0
    while [ $attempt -lt $max_attempts ]; do
        if docker exec deploysentry-postgres-1 pg_isready -U deploysentry -d deploysentry >/dev/null 2>&1; then
            break
        fi
        attempt=$((attempt + 1))
        sleep 1
    done

    if [ $attempt -eq $max_attempts ]; then
        log_error "PostgreSQL failed to start within 30 seconds"
        exit 1
    fi

    log_success "Development services started and ready"
}

# Run database migrations
run_migrations() {
    log_info "Running database migrations..."

    cd "$PROJECT_ROOT"

    # Source the .env file
    set -a
    source .env
    set +a

    # Run migrations
    make migrate-up

    log_success "Database migrations completed"
}

# Install dependencies
install_dependencies() {
    log_info "Installing Go dependencies..."
    cd "$PROJECT_ROOT"
    go mod download
    log_success "Go dependencies installed"

    log_info "Installing web dependencies..."
    cd "$PROJECT_ROOT/web"
    npm ci --ignore-scripts
    log_success "Web dependencies installed"
}

# Build the project
build_project() {
    log_info "Building project..."

    cd "$PROJECT_ROOT"

    # Build API
    log_info "Building API server..."
    go build -o bin/deploysentry-api ./cmd/api

    # Build CLI
    log_info "Building CLI..."
    go build -o bin/deploysentry ./cmd/cli

    log_success "Project built successfully"
}

# Run tests
run_tests() {
    log_info "Running tests..."

    cd "$PROJECT_ROOT"

    # Run unit tests
    log_info "Running unit tests..."
    make test-unit

    log_success "Tests passed"
}

# Create initial data
create_initial_data() {
    log_info "Setting up initial development data..."

    # This would create sample organizations, projects, flags, etc.
    # For now, we'll just ensure the server can start
    log_success "Initial data setup completed"
}

# Print startup instructions
print_startup_instructions() {
    cat << EOF

${GREEN}🎉 Development environment setup complete!${NC}

${BLUE}To start developing:${NC}

1. Start the API server:
   ${YELLOW}make run-api${NC}

2. Start the web dashboard (in another terminal):
   ${YELLOW}make run-web${NC}

3. Access the services:
   • API Server: ${BLUE}http://localhost:8080${NC}
   • Web Dashboard: ${BLUE}http://localhost:3000${NC}
   • Health Check: ${BLUE}http://localhost:8080/health${NC}
   • Metrics: ${BLUE}http://localhost:8080/metrics${NC}

${BLUE}Useful commands:${NC}
   • Run tests: ${YELLOW}make test${NC}
   • Stop services: ${YELLOW}make dev-down${NC}
   • View logs: ${YELLOW}docker-compose -f deploy/docker-compose.yml logs -f${NC}
   • Reset database: ${YELLOW}make migrate-down && make migrate-up${NC}

${BLUE}CLI Tool:${NC}
   • ${YELLOW}./bin/deploysentry --help${NC}

${GREEN}Happy coding! 🚀${NC}
EOF
}

# Main setup function
main() {
    echo -e "${BLUE}"
    cat << 'EOF'
  ____             _              ____            _
 |  _ \  ___ _ __ | | ___  _   _ / ___|  ___ _ __ | |_ _ __ _   _
 | | | |/ _ \ '_ \| |/ _ \| | | | \___ \ / _ \ '_ \| __| '__| | | |
 | |_| |  __/ |_) | | (_) | |_| |  ___) |  __/ | | | |_| |  | |_| |
 |____/ \___| .__/|_|\___/ \__, | |____/ \___|_| |_|\__|_|   \__, |
            |_|           |___/                             |___/
EOF
    echo -e "${NC}"
    echo -e "${BLUE}Development Environment Setup${NC}"
    echo ""

    check_prerequisites
    install_migrate
    generate_env_file
    start_services
    install_dependencies
    run_migrations
    build_project
    run_tests
    create_initial_data
    print_startup_instructions
}

# Handle script interruption
trap 'log_error "Setup interrupted"; exit 1' INT TERM

# Run main function
main "$@"